spring:
  application:
    name: mkkang-backend
  profiles:
    include: oauth
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/rootdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PW}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
      ssl:
        enabled: true
jwt:
  accesstoken:
    secretkey: ${ACCESS_SECRET_KEY}
    expiration: 300
  refreshtoken:
    secretkey: ${REFRESH_SECRET_KEY}
    expiration: 3600

client:
  ip: ${CLIENT_IP}
  port: ${CLIENT_PORT}

logging:
  level:
    root: INFO
    kr.mkkang.mkkangbackend: DEBUG