spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile,email
            redirect-uri: ${REDIRECT_URL_DOMAIN}/login/oauth2/code/google